### ISSUE TITLE
GDAL Dependencies Missing in Docker Build

### ISSUE THREAD

**Issue by JonnyDawe** [antarctica/PolarRoute-server#38]
### Description
The Docker build is failing when attempting to install Fiona (a dependency of polar-route) due to missing GDAL system dependencies. The error occurs during pip installation:

```CRITICAL:root:A GDAL API version must be specified. Provide a path to gdal-config using a GDAL_CONFIG environment variable or use a GDAL_VERSION environment variable.```

### Current Behavior
- Docker build fails during pip install
- Fiona package cannot be installed due to missing GDAL configuration
- Build process exits with error code 1

### Environment
- **OS**: macOS Sonoma V14.7.1
- **Docker Desktop Version**: 4.35.1

**Comment by davidwilby** [comment]
Arg, I'll look at this now, thanks for the report. This works on Ubuntu so unsure why this doesn't work on OSX so far.

**Comment by davidwilby** [comment]
Thanks, this is a little difficult to debug since I can't replicate it on my machine.

```docker
RUN apt-get update && apt-get install -y \
    gdal-bin \
    libgdal-dev \
    && rm -rf /var/lib/apt/lists/*
```

looks fine to me. Are these environment variables the right ones to set? Do you have a link on this?

The [Fiona docs](https://fiona.readthedocs.io/en/stable/install.html) and the error message above only mention setting `GDAL_CONFIG`

I've found I can install Fiona without these environment variables, but we could just include:

```docker
ENV GDAL_CONFIG=/usr/bin/gdal-config
```

Would you mind giving this a try?

**Comment by JonnyDawe** [comment]
yep that change seems to have worked fine on a complete fresh run:

```RUN apt-get update && apt-get install -y \
    gdal-bin \
    libgdal-dev \
    && rm -rf /var/lib/apt/lists/*

# Set GDAL environment variables
ENV GDAL_CONFIG=/usr/bin/gdal-config```
