### ISSUE TITLE
Admin interface is very slow

### ISSUE THREAD

**Issue by davidwilby** [antarctica/PolarRoute-server#48]
Some routes to speeding up:

https://docs.djangoproject.com/en/5.1/ref/contrib/admin/#django.contrib.admin.ModelAdmin.raw_id_fields

https://stackoverflow.com/questions/16755312/django-admin-change-form-load-quite-slow/16757065#16757065

**Comment by davidwilby** [comment]
I've tried limiting the queryset used in the routes admin list view (a0465f4) but with little success, hopefully switching to postgres will sort this out.

**Comment by davidwilby** [comment]
This is still an issue - look into this again.

**Comment by thomaszwagerman** [comment]
[Prefetching](https://docs.djangoproject.com/en/5.2/ref/models/querysets/#prefetch-related) the jobs (which are already sorted by datetime) removes some duplication. I think [`.only()`](https://docs.djangoproject.com/en/5.2/ref/models/querysets/#only) is causing a lot of extra queries because we're duplicating the list above when we can select on just "mesh" as a ForeignKey.

Rewriting the queryset reduces the number of queries:

![Image](https://github.com/user-attachments/assets/96b3b322-fb3c-45fe-a577-717380db96e8)

Not necessarily faster? But maybe I am not running this on a large enough number of entries to notice the difference.
